### PR TITLE
[KOGITO-9321] Testing Operator using Order SWF example

### PR DESCRIPTION
**Pull request by davidesalerno**

### CODE REVIEW

**Review by ederign — CHANGES_REQUESTED** [review]
@davidesalerno, this PR is great, but I believe it is not the best repo.

The idea behind kie-samples is to put here 'no code' examples that appear on the front page of kubesmarts.

I our scenario, the CRs will be hidden from the user and generated by the operator (on the backend)

Maybe we should move this to kogito examples? (that I assume will be renamed for sonata flow examples)

**Comment by ederign** [comment]
This is where we use those samples: https://start.kubesmarts.org/dev/#/sample-catalog

**Comment by caponetto** [comment]
Can we close this PR, @davidesalerno?

**Comment by davidesalerno** [comment]
Closing this in favor of [kogito-examples#1707](https://github.com/kiegroup/kogito-examples/pull/1707)

**Pull request closed without merging**
